 * Serving Flask app 'flasky' (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/flask/cli.py", line 995, in main
    cli.main(args=sys.argv[1:])
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/flask/cli.py", line 862, in run_command
    extra_files=extra_files,
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 991, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app 'flasky' (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/flask/cli.py", line 995, in main
    cli.main(args=sys.argv[1:])
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/flask/cli.py", line 862, in run_command
    extra_files=extra_files,
  File "/home/sara-saraya/Documents/Flask/Blog/.venv/lib64/python3.6/site-packages/werkzeug/serving.py", line 991, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
